<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

$owApp = OntoWiki::getInstance();

// this is the standard template data
$templateData   = $this->templateData;
$title = $this->literal(array('uri' => $this->modelUri, 'property' => EF_RDFS_NS . 'label', 'plain' => true));
$literalTemplate = basename($this->literal(array('property' => EF_RDF_NS . 'type', 'plain' => true)));
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?= $title . ': ' . $this->title ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?= $this->generator ?>" />

    <link rel="alternate" type="application/rdf+xml" href="<?= $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?= $this->pingbackUrl ?>" />

    <link rel="<?= $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?= $this->resourceUri?>" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap.css" rel="stylesheet" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/style.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/css/rdform.css'; ?>" rel="stylesheet" />
    <link type="text/css" href="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/css/smoothness/jquery-ui.custom.min.css'; ?>" rel="stylesheet" />

    <!-- jQuery -->
    <script type="text/javascript" src="<?= $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }
      @font-face{
		font-family:'Glyphicons Halflings';
		src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot);
		src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.woff) format('woff'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.ttf) format('truetype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format('svg')
		}
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<?php
    // includes the GA header script
    // includes the exhibit header links
    // other head scripts
    $this->headScript();
?>
</head>

<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?= ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
<div class="container">

    <header class="header">
        
        <?php
        $navResource = $this->templateOptions()->getValue('http://rdfs.org/ns/void#rootResource');
        $navOptions = array(
            'navResource' => $navResource,
            //'navId' => 'nav-main',
            'activeUrl' => $this->resourceUri,
            'listClass' => 'list-inline',
            //'navClass' => 'navbar'
        );
        ?>

        <div class="pull-right">

            <?php if ( $owApp->getUser()->isAnonymousUser() ) { ?>

                <form method="post" action="<?php echo $this->urlBase ?>application/login" class="search form-inline" name="locallogin">
                    <input type="hidden" name="logintype" value="locallogin" />
                    <input type="hidden" name="redirect-uri" value="%2FAbout" />

                    <div class="form-group">
                        <label for="username" class="sr-only">Benutzername</label>
                        <input class="form-control" type="text" id="username" name="username" placeholder="Benutzername" />
                    </div>
                    <div class="form-group">
                        <label for="password" class="sr-only">Kennwort</label>
                        <input class="form-control" type="password" id="password" name="password" placeholder="Passwort" />
                    </div>

                    <button type="submit" class="btn btn-default">Anmelden</button>
                </form>

            <?php } else { ?>                

                <form class="search pull-right" action="<?php echo $this->urlBase ?>Suche.html" method="POST" role="search">
                    <input name="mode" type="hidden" value="person" />
                    <input name="q" class="search-field form-control" role="search" data-value="<?php if (isset($_POST['q'])) echo $_POST['q'] ?>" type="text" placeholder="<?= $this->_('search_search') ?> ..." />
                </form>

                <div class="nav menu main-menu pull-right">
                    <?= $this->navigationList($navOptions) ?>               
                </div>

            <?php }  ?>

        </div>

        <h1 class="title"><?= $title ?></h1>

    </header>

    <div class="container content-container">

    <?php if ( ! $owApp->getUser()->isAnonymousUser() ) { ?>

        <div class="menu pull-left">
            Angemeldet als: <?php echo $owApp->getUser()->getUsername(); ?> | 
            <a href="<?php echo $this->urlBase ?>application/logout">Abmelden</a>
        </div>

        <div id="menu" class="menu pull-right">            
            <a href="<?= $this->Url(array('uri' => $this->resourceUri, 'stayOnSite' => false)) ?>"><?= $this->_('backend') ?></a><!-- should always be displayed -->
            <?php 
            if ( $literalTemplate == "Person" || 
                 $literalTemplate == "Place" || 
                 $literalTemplate == "Position" ||
                 $literalTemplate == "School" ) : ?>
                | <a class="rdform-edit-btn" href="#"><?= $this->_('edit') ?></a>
                | <a class="rdform-new-btn" href="#"><?= $this->_('new') ?></a>
            <?php endif; ?>|
            <?= $this->_('language') ?>: <a href="?lang=de">de</a>|<a href="?lang=hu">hu</a>
        </div>
        <br clear="both" />
    <?php } ?>

    <?= $this->renderx($this->templateData); ?>

    </div>

    <hr>
    <footer>
        <?php
            $copy = $this->literal(array('uri' => $this->modelUri, 'property' => 'http://creativecommons.org/ns#attributionName'));
            if ($copy != null) :
        ?>
        <p>&copy; <?= date('Y') . ' ' . $copy ?></p>
        <?php endif ?>
    </footer>
</div> <!-- /container -->

<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.js"></script>
<!-- include promise for IE compatibility -->
<script type="text/javascript" src="//cdn.jsdelivr.net/g/es6-promise@1.0.0"></script>

<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/jquery.jsonrpcclient.js/jquery.jsonrpcclient.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/jsonld.js/js/jsonld.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/js/jquery-ui.custom.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/js/rdform.js'; ?>"></script>

<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/jsonread.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/owrdform.js'; ?>"></script>

<script language="JavaScript">
    var urlBase = '<?php echo $this->urlBase ?>';
    var modelIri = '<?= $this->modelUri ?>';
    var resourceTemplate = '<?php echo $literalTemplate ?>';
    var resourceUri = '<?php echo $this->resourceUri ?>';
</script>

<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/browser.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/site.js"></script>

<input type="hidden" id="urlBase" value="<?php echo $this->urlBase ?>" />
<input type="hidden" id="modelIri" value="<?php echo $this->modelUri ?>" />
<input type="hidden" id="resourceTemplate" value="<?php echo $literalTemplate ?>" />    

</body>
</html>

