<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

// this is the standard template data
$templateData   = $this->templateData;
$title = $this->literal(array('uri' => $this->modelUri, 'property' => EF_RDFS_NS . 'label', 'plain' => true));
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?= $title . ': ' . $this->title ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?= $this->generator ?>" />

    <link rel="alternate" type="application/rdf+xml" href="<?= $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?= $this->pingbackUrl ?>" />

    <link rel="<?= $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?= $this->resourceUri?>" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap.css" rel="stylesheet" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/style.css" rel="stylesheet" />

    <!-- jQuery -->
    <script type="text/javascript" src="<?= $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<?php
    // includes the GA header script
    // includes the exhibit header links
    // other head scripts
    $this->headScript();
?>
</head>

<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?= ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
</hr>
<div class="container">
<h1><?= $title ?></h1>
<div id="menu">
<!-- <a href="<?= $this->Url($this->resourceUri) ?>">Bearbeiten</a> | -->
<a href="http://pfarrerbuch.de/About">Über das Projekt</a> | 
<a href="http://pfarrerbuch.de/Suche">Suche</a>
</div>

    <?= $this->renderx(); ?>

    <hr>
    <footer>
        <?php
            $copy = $this->literal(array('uri' => $this->modelUri, 'property' => 'http://creativecommons.org/ns#attributionName'));
            if ($copy != null) :
        ?>
        <p>&copy; <?= date('Y') . ' ' . $copy ?></p>
        <?php endif ?>
    </footer>
</div> <!-- /container -->

<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.js"></script>

</body>
</html>

