<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * example site extension layout template
 */

$owApp = OntoWiki::getInstance();

// this is the standard template data
$templateData   = $this->templateData;
$title = $this->literal(array('uri' => $this->modelUri, 'property' => EF_RDFS_NS . 'label', 'plain' => true));
$literalType = basename($this->literal(array('property' => EF_RDF_NS . 'type', 'plain' => true)));
?><!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta charset="UTF-8">
    <title><?= $title . ': ' . $this->title ?></title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="generator" content="<?= $this->generator ?>" />

    <link rel="alternate" type="application/rdf+xml" href="<?= $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?= $this->pingbackUrl ?>" />

    <link rel="<?= $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>" href="<?= $this->resourceUri?>" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/bootstrap.css" rel="stylesheet" />
    <link type="text/css" href="<?= $this->baseUri ?>/css/style.css" rel="stylesheet" />
    <link type="text/css" href="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/css/rdform.css'; ?>" rel="stylesheet" />
    <link type="text/css" href="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/css/smoothness/jquery-ui.custom.min.css'; ?>" rel="stylesheet" />

    <!-- jQuery -->
    <script type="text/javascript" src="<?= $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>

    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }
      @font-face{
		font-family:'Glyphicons Halflings';
		src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot);
		src:url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.woff) format('woff'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.ttf) format('truetype'),url(<?= $owApp->extensionManager->getComponentUrl('rdform') ?>public/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format('svg')
		}
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

<?php
    // includes the GA header script
    // includes the exhibit header links
    // other head scripts
    $this->headScript();
?>
</head>

<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?= ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>
<div class="container">
<h1><?= $title ?></h1>
    <?php
    $navResource = $this->templateOptions()->getValue('http://rdfs.org/ns/void#rootResource');
    $navOptions = array(
        'navResource' => $navResource,
        //'navId' => 'nav-main',
        'activeUrl' => $this->resourceUri,
        'listClass' => 'list-inline',
        //'navClass' => 'navbar'
    );
    ?>
<div id="menu">
    <?= $this->navigationList($navOptions) ?>
    <?php if ( $literalType == "Person" ) : ?>
                <a id="rdform-edit-btn" href="#">Bearbeiten</a>
                <!--<a id="rdform-new-btn" href="#">Neu</a> |-->
        <?php else : ?>
                <a href="<?= $this->Url(array('uri' => $this->resourceUri, 'stayOnSite' => false)) ?>">Bearbeiten</a>
        <?php endif; ?>
</div>


    <?= $this->renderx($this->templateData); ?>

    <hr>
    <footer>
        <?php
            $copy = $this->literal(array('uri' => $this->modelUri, 'property' => 'http://creativecommons.org/ns#attributionName'));
            if ($copy != null) :
        ?>
        <p>&copy; <?= date('Y') . ' ' . $copy ?></p>
        <?php endif ?>
    </footer>
</div> <!-- /container -->

<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/bootstrap.js"></script>

<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/jquery.jsonrpcclient.js/jquery.jsonrpcclient.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/jsonld.js/js/jsonld.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/js/jquery-ui.custom.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/lib/rdform/js/rdform.js'; ?>"></script>

<script type="text/javascript" src="<?php echo $owApp->extensionManager->getComponentUrl('rdform') . 'js/jsonread.js'; ?>"></script>

<script language="JavaScript">
    var urlBase = '<?php echo $this->urlBase ?>';
    var modelIri = '<?= $this->modelUri ?>';
    var resourceIri = '<?= $this->resourceUri ?>';
    //alert(urlBase);
    //alert("<?php echo $this->urlBase ?>");    
</script>

<script type="text/javascript" src="<?php echo $this->baseUri ?>/js/site.js"></script>

<input type="hidden" id="literalType" label="literalType" value="<?php echo $literalType; ?>" />
<input type="hidden" id="urlBase" value="<?php echo $this->urlBase ?>" />
<input type="hidden" id="modelIri" label="model" value="<?php echo $this->modelUri ?>" />
<input type="hidden" id="resourceIri" label="resource" value="<?php echo $this->resourceUri ?>" />
<input type="hidden" id="resourceId" label="resource" value="<?php echo abs( basename($this->resourceUri) ) ?>" />
<input type="hidden" id="redirectUri" label="redirectUri" value="<?php echo $this->resourceUri ?>" />
<input type="hidden" id="dataHash" label="dataHash" />
<input type="hidden" id="editable" disabled="true" />

</body>
</html>

