<?php
$staffingQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$staffingQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$staffingQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$staffingQuery.= 'SELECT DISTINCT ?resourceUri ?event ?ort ?bezeichnung ?start ?ende ?comment' . PHP_EOL;
$staffingQuery.= 'WHERE {' . PHP_EOL;
$staffingQuery.= '  <' . $this->resourceUri . '> hp:hasPosition ?resourceUri .' . PHP_EOL;
$staffingQuery.= '  ?resourceUri hp:place ?ortRes .' . PHP_EOL;
$staffingQuery.= '  OPTIONAL {' . PHP_EOL;
$staffingQuery.= '      { ?resourceUri rdfs:label ?bezeichnung . }' . PHP_EOL;
$staffingQuery.= '      UNION { ?resourceUri hp:positionDesignation ?bezeichnung . }' . PHP_EOL;
$staffingQuery.= '  }' . PHP_EOL;
$staffingQuery.= '  ?ortRes rdfs:label ?ort .' . PHP_EOL; // Diese Zeile könnte man auch mit dem Titlehelper machen
$staffingQuery.= '  OPTIONAL {' . PHP_EOL;
$staffingQuery.= '      ?event rdf:subject <' . $this->resourceUri . '> ;' . PHP_EOL;
$staffingQuery.= '             rdf:predicate hp:hasPosition ;' . PHP_EOL;
$staffingQuery.= '             rdf:object ?resourceUri .' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event hp:start ?start .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event hp:end ?ende .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event rdfs:comment ?comment .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '  }' . PHP_EOL;
$staffingQuery.= '} ORDER BY ASC(?start) ASC(?ende)' . PHP_EOL;

$attendingQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$attendingQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$attendingQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$attendingQuery.= 'SELECT DISTINCT ?resourceUri ?ort ?schulName ?start ?ende ?comment' . PHP_EOL;
$attendingQuery.= 'WHERE {' . PHP_EOL;
$attendingQuery.= '  <' . $this->resourceUri . '> hp:attendedSchool ?resourceUri .' . PHP_EOL;
$attendingQuery.= '  ?resourceUri hp:place ?ortRes .' . PHP_EOL;
$attendingQuery.= '  { ?resourceUri rdfs:label ?schulName . }' . PHP_EOL; // Diese Zeile könnte man auch mit dem Titlehelper machen
$attendingQuery.= '  UNION { ?resourceUri hp:nameOfSchool ?schulName . }' . PHP_EOL;
$attendingQuery.= '  { ?ortRes rdfs:label ?ort . }' . PHP_EOL; // Diese Zeile könnte man auch mit dem Titlehelper machen
$attendingQuery.= '  UNION {?ortRes hp:nameOfPlace ?ort . }' . PHP_EOL;
$attendingQuery.= '  OPTIONAL {' . PHP_EOL;
$attendingQuery.= '      ?event rdf:subject <' . $this->resourceUri . '> ;' . PHP_EOL;
$attendingQuery.= '             rdf:predicate hp:attendedSchool ;' . PHP_EOL;
$attendingQuery.= '             rdf:object ?resourceUri .' . PHP_EOL;
$attendingQuery.= '      OPTIONAL {' . PHP_EOL;
$attendingQuery.= '          ?event hp:start ?start .' . PHP_EOL;
$attendingQuery.= '      }' . PHP_EOL;
$attendingQuery.= '      OPTIONAL {' . PHP_EOL;
$attendingQuery.= '          ?event hp:end ?ende .' . PHP_EOL;
$attendingQuery.= '      }' . PHP_EOL;
$attendingQuery.= '      OPTIONAL {' . PHP_EOL;
$attendingQuery.= '          ?event rdfs:comment ?comment .' . PHP_EOL;
$attendingQuery.= '      }' . PHP_EOL;
$attendingQuery.= '  }' . PHP_EOL;
$attendingQuery.= '} ORDER BY ASC(?start) ASC(?ende)' . PHP_EOL;
// evtl. noch den schoolType abfragen

$childQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$childQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$childQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$childQuery.= 'SELECT ?resourceUri' . PHP_EOL;
$childQuery.= 'WHERE {' . PHP_EOL;
$childQuery.= '  <' . $this->resourceUri . '> hp:child ?resourceUri .' . PHP_EOL;
$childQuery.= '}' . PHP_EOL;
?>

<div class="container row">
	<div class="col-md-8">

	<?php $lastName = $this->literal(array('property' => 'foaf:lastName')); ?>
	<?php $firstName = $this->literal(array('property' => 'foaf:firstName')); ?>
	<?php $name = $this->literal(array('property' => 'foaf:name')); ?>
	<?php $birthName = $this->literal(array('property' => 'foaf:birthName', 'prefix' => ' (geb. ', 'suffix' => ')')) // hat keiner ?></h3>
	<h3>
	<?php if ($lastName || $firstName) : ?>
	<?= $lastName . ', ' . $firstName ?>
	<?php elseif ($name) : ?>
	<?= $name ?>
	<?php endif; ?>
	<?= $birthName ?>
	</h3>
	<div>
	<?= $this->literal(array('property' => 'hp:nameVariant', 'tag' => 'em', 'prefix' => 'Namens Variante: ')) ?>
	</div>

	<div>
	<?php $dob = $this->literal(array('property' => 'hp:birthDate', 'tag' => 'span', 'node' => true)) ?>
	<?php if ($dob) : ?>
	* <?= $this->date($dob) ?>
	<?php endif; ?>

	<?= $this->query(array('where' => '<' . $this->resourceUri . '> hp:birthPlace ?resourceUri', 'template' => 'resource')) ?>

        –

	<?php $dod = $this->literal(array('property' => 'hp:dateOfDeath', 'tag' => 'span', 'node' => true)) ?>
	<?php if ($dod) : ?>
	† <?= $this->date($dod) ?>
	<?php endif; ?>

	<?= $this->query(array('where' => '<' . $this->resourceUri . '> hp:placeOfDeath ?resourceUri', 'template' => 'resource')) ?>
	</div>

	<dl>
	<?php $dOfBabtism =  $this->literal(array('property' => 'hp:dayOfBaptism', 'tag' => 'span', 'node' => true)) ?>
	<?php if ($dOfBabtism) : ?>
	<dt>Taufe</dt>
	<dd>
	<?= $this->date($dOfBabtism) ?>
	</dd>
	<?php endif; ?>

	<?= $this->literal(array('property' => 'hp:placeOfBaptism', 'tag' => 'span', 'prefix' => ' in ')) ?>
	</dd>

	<dl>
	<?php
	$dOfFuneral = $this->literal(array('property' => 'hp:dayOfFuneral', 'tag' => 'span', 'node' => true));
	$burialPlace = $this->literal(array('property' => 'hp:burialPlace', 'tag' => 'span', 'prefix' => ' in '));
	?>
	<?php if ($dOfFuneral || $burialPlace) : ?>
	<dt>Beerdigung</dt>
	<dd>
	<?php if ($dOfFuneral) : ?>
	    <?= $this->date($dOfFuneral) ?>
	<?php endif; ?>
	<?= $burialPlace ?>
	</dd>
	<?php endif; ?>
	</dl>

	<?php
	$dOfOrdination = $this->literal(array('property' => 'hp:dateOfOrdination', 'tag' => 'span', 'node' => true));
	$pOfOrdination = $this->query(array('where' => '<' . $this->resourceUri . '> hp:placeOfOrdination ?resourceUri', 'template' => 'resource'));
	$ordinator = $this->query(array('where' => '<' . $this->resourceUri . '> hp:ordinator ?resourceUri', 'template' => 'resource', 'prefix' => '(', 'suffix' => ')'));
	?>
	<?php if ($dOfOrdination || $pOfOrdination) : ?>
	<dl>
	<dt>Ordination</dt>
	<dd>
	<?php if ($dOfOrdination) : ?>
	<?= $this->date($dOfOrdination) ?>
	<?php endif; ?>
        <?= $pOfOrdination ?>
        <?= $ordinator ?>
	</dd>
	<?php endif; ?>

	<?= $this->querylist($staffingQuery, 'local/items/staffing.phtml', array('mode' => 'person')) ?>

	<?php $dOfRetirement = $this->literal(array('property' => 'hp:dateOfRetirement', 'tag' => 'span', 'node' => true)); ?>
	<?php $pOfRetirement = $this->literal(array('property' => 'hp:placeOfRetirement', 'tag' => 'span', 'prefix' => ' in ')); ?>
	<?php if ($dOfRetirement || $pOfRetirement) : ?>
	<dt>Emeriterung</dt>
	<dd>
	<?php if ($dOfRetirement) : ?>
	<?= $this->date($dOfRetirement) ?>
	<?php endif; ?>
	<?= $pOfRetirement ?>
	</dd>
	<?php endif; ?>

	<?php if ($pOfRetirement) : ?>
	<dd>
	    in 
	<?= ($pOfRetirement) ?>
	</dd>
	<?php endif; ?>
	</dl>
	</div>

	<div class="col-md-4">
        <img alt="Foto des Pfarrers" class="img-responsive img-thumbnail" src="<?= $this->wikiBaseUrl ?>site/img/pfarrer.png" />

	<!-- Abstand -->

	</hr>

	<dl>
	<?php $mother = $this->query(array('where' => '<' . $this->resourceUri . '> hp:mother ?resourceUri', 'template' => 'person')) ?>
	<?php $father = $this->query(array('where' => '<' . $this->resourceUri . '> hp:father ?resourceUri', 'template' => 'person')) ?>
	<?php if ($father) : ?>
	<dt>Vater</dt>
	<?= $father ?>
	<?php endif; ?>
	<?php if ($mother) : ?>
	<dt>Mutter</dt>
	<?= $mother ?>
	<?php endif; ?>
	</dl>

	<h4>Bildungsweg</h4>
	<dl>
	<?= $this->querylist($attendingQuery, 'local/items/attendingSchool.phtml') ?>
	</dl>

<!--//
	<h4>Tätigkeiten</h4>
	<dl>
	 <dt>1. Februar 1250 – 24. Dezember 1714</dt>
	 <dd>Hilfslehrer …</dd>
        </dl>
//-->

	<hr />
	<h4>Kinder</h4>
	<ul>
	<?= $this->querylist($childQuery, 'local/items/person.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>' )) ?>
	</ul>
	</div>
</div>

<hr/>
<h4>Bemerkungen</h4>
<?= $this->literals(array('property' => 'rdfs:comment', 'tag' => 'div', 'class' => 'content')) ?>

<h4>Bearbeitungs Bemerkungen</h4>
<?= $this->literals(array('property' => 'hp:editorsComment', 'tag' => 'div', 'class' => 'content')) ?>

<h4>Quellen und Literatur</h4>
<?= $this->literals(array('property' => 'hp:source', 'tag' => 'div', 'class' => 'content')) ?>
