<?php
$positionQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$positionQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$positionQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$positionQuery.= 'SELECT DISTINCT ?resourceUri ?bezeichnung' . PHP_EOL;
$positionQuery.= 'WHERE {' . PHP_EOL;
$positionQuery.= '  ?resourceUri hp:place <' . $this->resourceUri . '> ;' . PHP_EOL;
$positionQuery.= '               a hp:Position .' . PHP_EOL;
$positionQuery.= '  {?resourceUri hp:positionDesignation ?bezeichnung }' . PHP_EOL;
$positionQuery.= '  UNION {?resourceUri rdfs:label ?bezeichnung }' . PHP_EOL;
$positionQuery.= '} ORDER BY ?bezeichnung' . PHP_EOL;

$schoolQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$schoolQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$schoolQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$schoolQuery.= 'SELECT DISTINCT ?resourceUri ?bezeichnung' . PHP_EOL;
$schoolQuery.= 'WHERE {' . PHP_EOL;
$schoolQuery.= '  ?resourceUri hp:place <' . $this->resourceUri . '> ;' . PHP_EOL;
$schoolQuery.= '             a hp:School .' . PHP_EOL;
$schoolQuery.= '  {?resourceUri hp:nameOfSchool ?bezeichnung }' . PHP_EOL;
$schoolQuery.= '  UNION {?resourceUri rdfs:label ?bezeichnung }' . PHP_EOL;
$schoolQuery.= '} ORDER BY ?bezeichnung' . PHP_EOL;
?>
<div class="container row-fluid">
<div class="col-md-8">
<h3><?= $this->title ?></h3>

<h4>Liste der Pfarrstellen</h4>
<ul>
<?= $this->querylist($positionQuery, 'local/items/resource.phtml', array('ort' => $this->title), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
</ul>

</div>

<div class="col-md-4">

<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org feed template
 *
 * arranges the news feed for the resource
 */

// prepare module options
$map = trim($this->module('map', array('noChrome' => true)));
?>
<img alt="Foto der Kirche" class="img-responsive img-thumbnail" src="<?= $this->wikiBaseUrl ?>site/img/kirche.png" />
<hr/>
<?php if (!empty($map)): ?>
<?= $map; ?>
<?php else: ?>
<div class="alert alert-info">
Es wurden keine Kartendaten für diesen Ort hinterlegt
</div>
<?php endif; ?>
<hr/>
<h5>Liste der Schulen und Universitäten</h5>
<ul>
<?= $this->querylist($schoolQuery, 'local/items/resource.phtml', array('ort' => $this->title), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
</ul>

<!-- Personen Geboren in … -->

<!-- Personen Gestorben in … -->

<!-- Taufort … -->
<!-- Beerdigt in … -->
</div>
</div>
