<?php
$staffingQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$staffingQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$staffingQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$staffingQuery.= 'SELECT ?resourceUri ?start ?ende ?comment' . PHP_EOL;
$staffingQuery.= 'WHERE {' . PHP_EOL;
$staffingQuery.= '  ?resourceUri hp:hasPosition <' . $this->resourceUri . '> .' . PHP_EOL;
$staffingQuery.= '  OPTIONAL {' . PHP_EOL;
$staffingQuery.= '      ?event rdf:subject ?resourceUri ;' . PHP_EOL;
$staffingQuery.= '             rdf:predicate hp:hasPosition ;' . PHP_EOL;
$staffingQuery.= '             rdf:object <' . $this->resourceUri . '> .' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event hp:start ?start .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event hp:end ?ende .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '      OPTIONAL {' . PHP_EOL;
$staffingQuery.= '          ?event rdfs:comment ?comment .' . PHP_EOL;
$staffingQuery.= '      }' . PHP_EOL;
$staffingQuery.= '  }' . PHP_EOL;
$staffingQuery.= '} ORDER BY ASC(?start) ASC(?ende)' . PHP_EOL;
?>
<h3><?= $this->query(array('where' => '<' . $this->resourceUri . '> hp:place ?resourceUri', 'template' => 'resource')) ?> <?= $this->title ?></h3>

<dl>
<dt>Liste der Pfarrer die diese Stelle inne hatten</dt>
<dd>
<dl>
<?= $this->querylist($staffingQuery, 'local/items/staffing.phtml', array('mode' => 'position')) ?>
</dl>
</dd>
</dl>
