<h3>
<?= $this->literal(array('property' => 'hp:nameOfSchool')) ?> 
<?= $this->literal(array('property' => 'hp:schoolType')) ?> 
<?= $this->query(array('where' => '<' . $this->resourceUri . '> hp:place ?resourceUri', 'template' => 'resource')) ?>
</h3>

<?php
$teacherQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$teacherQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$teacherQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$teacherQuery.= 'SELECT ?resourceUri' . PHP_EOL;
$teacherQuery.= 'WHERE {' . PHP_EOL;
$teacherQuery.= '  ?resourceUri hp:hasPosition <' . $this->resourceUri . '> .' . PHP_EOL;
$teacherQuery.= '} LIMIT 20' . PHP_EOL;

$studentQuery = 'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>' . PHP_EOL;
$studentQuery.= 'PREFIX hp: <http://purl.org/voc/hp/>' . PHP_EOL;
$studentQuery.= 'PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>' . PHP_EOL;
$studentQuery.= 'SELECT ?resourceUri' . PHP_EOL;
$studentQuery.= 'WHERE {' . PHP_EOL;
$studentQuery.= '  ?resourceUri hp:attendedSchool <' . $this->resourceUri . '> .' . PHP_EOL;
$studentQuery.= '} LIMIT 20' . PHP_EOL;
?>

<h4>Liste der Personen die an dieser Universität/Schule gelehrt haben</h4>
<ul>
<?= $this->querylist($teacherQuery, 'local/items/person.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
</ul>


<h4>Liste der Personen die an dieser Universität/Schule gelernt haben</h4>
<ul>
<?= $this->querylist($studentQuery, 'local/items/person.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
</ul>
