<?php

$searchText = null;
$m = null;
if (isset($_POST['q'])) {
    $searchText = $_POST['q'];
}
if (isset($_POST['mode'])) {
    $m = $_POST['mode'];
}

?>

<h3>Suche</h3>
<form method="post">
    <select name="mode">
        <option value="name" <?= ($m=='name')?'selected':'' ?>>Name</option>
        <option value="ort" <?= ($m=='ort')?'selected':'' ?>>Ort</option>
    </select>
    <input name="q" type="text" value="<?= $searchText ?>"/>
    <input type="submit"/>
</form>

<?php

$query = new Erfurt_Sparql_Query2();
$foafIri = new Erfurt_Sparql_Query2_IriRef('http://xmlns.com/foaf/0.1/');
$hpIri = new Erfurt_Sparql_Query2_IriRef('http://purl.org/voc/hp/');
$rdfsIri = new Erfurt_Sparql_Query2_IriRef('http://www.w3.org/2000/01/rdf-schema#');
$foafPrefix = new Erfurt_Sparql_Query2_Prefix('foaf', $foafIri);
$hpPrefix = new Erfurt_Sparql_Query2_Prefix('hp', $hpIri);
$rdfsPrefix = new Erfurt_Sparql_Query2_Prefix('rdfs', $rdfsIri);
$query->addPrefix($foafPrefix);
$query->addPrefix($hpPrefix);
$query->addPrefix($rdfsPrefix);

$store = Erfurt_App::getInstance()->getStore();
$resourceUriVar  = new Erfurt_Sparql_Query2_Var('resourceUri');

if ($m == 'name') {
    $nameVar  = new Erfurt_Sparql_Query2_IriRef('name', $foafPrefix);
    $elements = $store->getSearchPatternWithNode($searchText, $nameVar);

    $pVar  = new Erfurt_Sparql_Query2_IriRef('isPastor', $hpPrefix);
    $oVar  = new Erfurt_Sparql_Query2_Var('isPastor');
    $elements[] = new Erfurt_Sparql_Query2_Triple($resourceUriVar, $pVar, $oVar);
    $elements[] = new Erfurt_Sparql_Query2_Filter(
        new Erfurt_Sparql_Query2_ConditionalOrExpression(
            array(
                new Erfurt_Sparql_Query2_Equals($oVar, new Erfurt_Sparql_Query2_BooleanLiteral(true)),
                new Erfurt_Sparql_Query2_Equals($oVar, new Erfurt_Sparql_Query2_NumericLiteral(1)),
            )
        )
    );
    $query->addElements($elements);

} else if ($m == 'ort') {
    $nameOfPlaceOption = new Erfurt_Sparql_Query2_GroupGraphPattern();
    $nameOfPlaceVar  = new Erfurt_Sparql_Query2_IriRef('nameOfPlace', $hpPrefix);
    $nameOfPlaceOption->addElements($store->getSearchPatternWithNode($searchText, $nameOfPlaceVar));

    $typePlaceOption = new Erfurt_Sparql_Query2_GroupGraphPattern();
    $typeVar  = new Erfurt_Sparql_Query2_IriRef('Place', $hpPrefix);
    $rdfsLabelVar  = new Erfurt_Sparql_Query2_IriRef('label', $rdfsPrefix);
    $a = new Erfurt_Sparql_Query2_A();
    $typePlaceOption->addElement(new Erfurt_Sparql_Query2_Triple($resourceUriVar, $a, $typeVar));
    $typePlaceOption->addElements($store->getSearchPatternWithNode($searchText, $rdfsLabelVar));

    $unionPattern = new Erfurt_Sparql_Query2_GroupOrUnionGraphPattern();
    $unionPattern->addElement($nameOfPlaceOption);
    $unionPattern->addElement($typePlaceOption);
    $query->addElement($unionPattern);
}

$query->addProjectionVar($resourceUriVar);
$query->setDistinct();

?>
<?php if ($m !== null) : ?>
    <span>Suche nach „<?= $searchText ?>“</span>
    <ul>
        <?= $this->querylist($query, 'local/items/resource.phtml', array(), array('prefix' => '<li>', 'suffix' => '</li>')) ?>
    </ul>
<?php else: ?>
    <span>Bitte wählen Sie die Art der Suche aus und geben Sie ihren Suchtext in das nebenstehende Feld ein.</span>
<?php endif; ?>
