<dt>
<?php if ($this->start && $this->ende) : ?>
<?= $this->date($this->start) ?> – <?= $this->date($this->ende) ?>
<?php elseif ($this->start && !$this->ende): ?>
<?= $this->date($this->start) ?> – 
<?php elseif (!$this->start && $this->ende) : ?>
 – <?= $this->date($this->ende) ?>
<?php else : ?>
 – 
<?php endif ?>
</dt>
</dt>
<dd>
<a href="<?= htmlentities($this->resourceUri) ?>">
    <?= $this->schulName ?>
    (<?= $this->ort ?>)
</a>
<em><?= $this->comment ?></em>
</dd>
