<a href="<?= htmlentities($this->resourceUri) ?>">
    <?= $this->literal(array('uri' => $this->resourceUri, 'property' => 'foaf:lastName')); ?>,
    <?= $this->literal(array('uri' => $this->resourceUri, 'property' => 'foaf:firstName')); ?>
</a>
<?php
/* This PHP tag is only to absorb the UNIX-newline */

/**
Such Repräsentation:
rdfs:label (Name inklusive Geburtsjahr und Ort) Angabe: ist Pfarrer durch Agaben <em>ev-luth. Pfarrer (Sachsen)</em>
 */
