<?php
$countryUri = $this->literal(array('uri' => $this->resourceUri, 'property' => 'hp:country', 'plain' => true));
if (!empty($countryUri)) {
    $countryLabel = "(" . $this->literal(array('uri' => $countryUri, 'property' => 'rdfs:label')) . ")";
} else {
    $countryLabel = "";
}
?>
<a href="<?= htmlentities($this->resourceUri) ?>"><?= $this->title ?> <?= $countryLabel ?></a>
<?php
/* This PHP tag is only to absorb the UNIX-newline */

/**
Such Repräsentation:
rdfs:label (Name inklusive Geburtsjahr und Ort) Angabe: ist Pfarrer durch Agaben <em>ev-luth. Pfarrer (Sachsen)</em>
 */
