<dt>
<?php if ($this->start && $this->ende) : ?>
<?= $this->date($this->start) ?> – <?= $this->date($this->ende) ?>
<?php elseif ($this->start && !$this->ende): ?>
<?= $this->date($this->start) ?> – 
<?php elseif (!$this->start && $this->ende) : ?>
 – <?= $this->date($this->ende) ?>
<?php else : ?>
 - 
<?php endif ?>
</dt>
<dd>
<a href="<?= htmlentities($this->resourceUri) ?>">
<?php if ($this->mode == 'person') : ?>
    <?= $this->ort ?>
    <?= $this->bezeichnung ?>
<?php elseif ($this->mode == 'position') : ?>
    <?= $this->title ?>
<?php endif; ?>
</a>
<em><?= $this->comment ?></em>
</dd>
