<dt>
<?php
$start = false;
$ende = false;
?>
<?php if ($this->start) : ?>
    <?php $start = $this->literal(array('uri' => $this->event, 'property' => 'hp:start', 'tag' => 'span', 'node' => true)) ?>
<?php endif ?>
<?php if ($this->ende) : ?>
    <?php $ende = $this->literal(array('uri' => $this->event, 'property' => 'hp:end', 'tag' => 'span', 'node' => true)) ?>
<?php endif ?>
<?php if ($start && $ende) : ?>
<?= $this->date($start) ?> – <?= $this->date($ende) ?>
<?php elseif ($start && !$ende): ?>
<?= $this->date($start) ?> – 
<?php elseif (!$start && $ende) : ?>
 – <?= $this->date($ende) ?>
<?php else : ?>
 – 
<?php endif ?>
</dt>
<dd>
<a href="<?= htmlentities($this->resourceUri) ?>">
<?php if ($this->mode == 'person') : ?>
    <?= $this->ort ?>
    <?= $this->bezeichnung ?>
<?php elseif ($this->mode == 'position') : ?>
    <?= $this->title ?>
<?php endif; ?>
</a>
<em><?= $this->comment ?></em>
</dd>
